add support for H100s
predibase/lorax pull request #111
Opened 2023-12-07 07:05 UTC by thelinuxkid

# What does this PR do?

add support for H100s

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Was this discussed/approved via a Github issue or the discord / slack channel? Please add a link
      to it if that's the case.
- [x] Did you write any new necessary tests?

## Who can review?

@arnavgarg1 
@tgaddair 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

 
 ## POC
![image](https://github.com/predibase/lorax/assets/459925/2930ccac-872f-427e-81ab-e5f112ae0bde)

2023-12-07 09:38 UTC, flozi00 commented
https://github.com/enricai/lorax/blob/58b3c0c7a97f3e43355af4965afc09668e58f571/Dockerfile#L40

Could you set the pytorch version in docker to 2.1.1 too ?

2023-12-07 15:59 UTC, thelinuxkid commented
> https://github.com/enricai/lorax/blob/58b3c0c7a97f3e43355af4965afc09668e58f571/Dockerfile#L40
> 
> Could you set the pytorch version in docker to 2.1.1 too ?

@flozi00 Done!!

2023-12-07 22:12 UTC, thelinuxkid commented
Build issue should be fixed now

2023-12-09 22:08 UTC, tgaddair commented on Dockerfile
> +    /opt/conda/bin/pip install torch==2.1.1+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118 ;; \
torchaudio and torchvision versions are out of sync, but I don't think they're needed anyway. I'll land as-is and remove these in a follow-up.

2023-12-09 22:09 UTC, tgaddair approved these changes
LGTM! I'll go ahead and land, and then do some robustness tests after the new image goes out.

2023-12-09 22:11 UTC, tgaddair commented on server/requirements.txt
> +zipp==3.17.0 ; python_version >= "3.9" and python_version < "4.0"
Looks like we lost `peft==0.4.0` somehow. Can you add this to the `pyproject.toml`?

2023-12-09 22:12 UTC, tgaddair requested changes
@thelinuxkid looks like based on the tests we actually need to add back `peft` as a dependency.

2023-12-09 22:14 UTC, tgaddair commented
@thelinuxkid alternatively, would you mind giving me edit access to the PR so I can make these changes while I test things out?

2023-12-10 00:54 UTC, thelinuxkid commented
@tgaddair just added, will wait for tests to see if they turn out OK this time

2023-12-10 05:44 UTC, tgaddair commented
Hey @thelinuxkid, apologies, but can you add these to `pyproject.toml` as well and update the other dep files:

```
boto3 = "^1.28.34"
urllib3 = "<=1.26.18"
```

2023-12-10 16:08 UTC, thelinuxkid commented
@tgaddair Done! Also gave you access as maintainer to our fork

2023-12-10 21:49 UTC, tgaddair approved these changes
Ran a few tests earlier today with these changes. Everything looks good on my end. Merging!

2023-12-10 21:49 UTC, merged

2023-12-11 16:01 UTC, thelinuxkid commented
Thanks @tgaddair ! When will this be available in the docker image? I'm not able to run with flash attn successfully. I build it but I still get an error that it doesn't exist when running it